[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/not-found.html"
  status = 404

[[redirects]]
  from = "/**/config.yml"
  to = "/config.yml"
  status = 200
